export const POST_ORIGINAL_LINK_REQUEST = 'POST_ORIGINAL_LINK_REQUEST';
export const POST_ORIGINAL_LINK_SUCCESS = 'POST_ORIGINAL_LINK_SUCCESS';
export const POST_ORIGINAL_LINK_ERROR = 'POST_ORIGINAL_LINK_ERROR';

export const CHANGE_VALUE = 'CHANGE_VALUE';